
   
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: QUZIHANWU
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#       - uses: lowlighter/metrics@latest
#         with:
#           filename: dist/metrics.plugin.languages.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_languages: yes
#           plugin_languages_ignored: >-
#             html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
#             gnuplot
#           plugin_languages_limit: 4
